import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";


export const metadata: Metadata = {
  title: "YourResumeScanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-r from-[#FFDA78] via-[#FBFBFB] to-[#FAFFAF] font-serif"
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
